Version 0.2.3

diff --git a/common b/common
--- a/common
+++ b/common
@@ -8,11 +8,22 @@ msg () {
 
 fatal () { msg "$@"; exit 1; }
 
+tempdir () {
+    : ${TMPDIR:="/tmp"}
+    tdbase=$TMPDIR/$USER
+    test -e $tdbase || mkdir -p $tdbase
+    td=$(mktemp -d $tdbase/$(basename $0).XXXXXX) || fatal "Could not create temp dir in $tdbase"
+    echo $td
+}
+
 normalpath () {
+    local s=$1
+    [[ $s == ${s::400} ]] || fatal "Option path too long"
+    [[ $s == ${s//[^[:print:]]/} ]] || fatal "Non-printables in path"
     dir=$(dirname "$1")
     bas=$(basename "$1")
     echo $(cd $dir && pwd)/$bas
 }
 
-irtk=/vol/vipdata/users/rahec/irtk/linux/bin
-niftyseg=/vol/vipdata/users/rahec/niftyseg/bin
+
+set -e   # Terminate script at first error
